### ISSUE TITLE
Release Empty

### ISSUE THREAD

**Issue by cyborgdoom** [ashish-chopra/ngx-gauge#1]
Fix your release package there is nothing in there. It doesn't install anything

**Comment by ashish-chopra** [comment]
I am sorry, yes release is empty by purpose. I was testing some bits of using it. I found release is not importable in angular CLI project due to some compilation issues. So working on those.

**Comment by askdrgui** [comment]
Do you have any idea when the release package is available?

**Comment by ashish-chopra** [comment]
In next couple of weeks, i will fix the issues and make it available.

Thanks
Ashish

**Comment by ashish-chopra** [comment]
Hello guys @cyborgdoom  and @askdrgui, I have just released 1.0.0-beta package in npm. Try it and post some issues you encountered. after settling up few more things, stable version will be released.

Thanks
Ashish
