### ISSUE TITLE
Problem with example from read.me not working in ionic

### ISSUE THREAD

**Issue by num3robis** [ashish-chopra/ngx-gauge#10]
Hi i'm doing exactly the code you gave in the read me file. But nothing appears. Even when i hard code the data in the html only the value is working, but no gauge. 
Please help me figure this out. Do you think your module works on ionic 3 ?

**Comment by ashish-chopra** [comment]
Thanks for trying the library and providing your interesting findings.

Actually, I have no idea of Ionic, therefore never kept it in mind while writing this library. But If you can help me to identify what needs to be taken care while developing angular code that works out of the box with Ionic, I will look into adding those changes here.

Regards
Ashish

**Comment by meenakarthik** [comment]
I'm using the gauge from the example in Ionic fine. Are you importing the NgxGaugeModule not only in the app.module.ts but also in whatever component/page.module.ts that you are using the gauge in?

**Comment by jchri853** [comment]
@num3robis I can confirm it works in an ionic3 application.  Here is an example of how I am using one. Make sure you have atributes specified in your .ts component 

.TS
    gaugeType = "full";
    gaugeLabel = "";

HTML
`   <ngx-gauge 
                   [type]="gaugeType"  
                   [value]="outerGaugevalue" 
                   [thick] = 5 
                   [min] =  0
                   [max] = 100
                   [min] =  0
                   [foregroundColor] = "rgb(255,255,255)"
                   [backgroundColor] = "rgba(54, 100, 100, 0.3)"
                   [label]="gaugeLabel"
                   [duration] = 5
                   [size] = 66
                   [cap] ="butt"  > 
              </ngx-gauge> `

**Comment by jchri853** [comment]
![screen shot 2018-02-05 at 2 15 33 pm](https://user-images.githubusercontent.com/3412424/35826677-0ac0747a-0a7f-11e8-9461-ca7194731d9f.png)

My only request (If possible :D)   To make the gauge lines vector, they look a little pixelated on retina devices.

**Comment by ashish-chopra** [comment]
Thanks @jchri853 I will look into pixelated issue. I found some useful resource https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio to incorporate and test with gauge to support retina displays.

By the way, how did you managed to get two concentric gauges with my library, I am curious to know!!

Cheers
Ashish

**Comment by fernandocode** [comment]
@num3robis ,

The library works perfectly with ionic.

I am using it in my project, with no problems and follows an [online example](https://stackblitz.com/edit/ionic-vb84cx?file=pages%2Fhome%2Fhome.html) for verification.

**Comment by fernandocode** [comment]
@jchri853  It may be interesting to open a new issue for your problem on retina screens.

And as has already been asked, how have you done to present gauges with this library?

**Comment by jchri853** [comment]
@fernandocode  @ashish-chopra its not "pretty" but it worked for me. Enjoy 

https://stackblitz.com/edit/ionic-jl3xc2
