### ISSUE TITLE
Angular 14 Support

### ISSUE THREAD

**Issue by danielehrhardt** [ashish-chopra/ngx-gauge#126]
Can you update your package json to support angular 14 without using --force

**Comment by ashish-chopra** [comment]
Hi Daniel,
I will do that this weekend.

Thanks
Ashish

**Comment by marcellkiss** [comment]
Please do that, thanks :)

**Comment by ashish-chopra** [comment]
Done. I haven't done extensive testing. If anything appears raise an issue.

Thank you!
