### ISSUE TITLE
Angular 15 Support

### ISSUE THREAD

**Issue by Corfus** [ashish-chopra/ngx-gauge#136]
It would be great if you could release a new version with angular 15 support.

**Comment by ashish-chopra** [comment]
Yes, I will plan it during these holidays. Thanks!

**Comment by afermon** [comment]
Hi @ashish-chopra 

Thank you for the component!

Any update to the Angular v15 compatible version?

**Comment by ashish-chopra** [comment]
Yes, it was long pending, sorry for the delays. I am travelling right now, will do it by 11 Feb positively.

**Comment by ashish-chopra** [comment]
It's done. Kindly update your package form npm using npm -i ngx-gauge
