### ISSUE TITLE
Angular 17 Support

### ISSUE THREAD

**Issue by Pertempto** [ashish-chopra/ngx-gauge#147]
```
npm ERR! While resolving: ngx-gauge@8.0.0
npm ERR! Found: @angular/common@17.0.2
```

**Comment by Pertempto** [comment]
@ashish-chopra what all would this involve?

**Comment by ashish-chopra** [comment]
hey @Pertempto I will be looking into it this week. Keep you posted. If you find anything useful for me to upgrade without much research, feel free to share.

**Comment by MatthiasWerning** [comment]
I recently upgraded my application to Angular 17 and I had no issues with the latest version of this library. So it might be safe to just adjust the Angular library peer and dev dependencies.

**Comment by ashish-chopra** [comment]
Perfect. Thanks for the heads up

**Comment by deepu93** [comment]
recently started a new application in angular 17 , is there anyway we can use this module with @angular/common": "^17.0.0 . currently facing errors while installing ngx-gauge@8.0.0

**Comment by Pertempto** [comment]
We're currently stuck with using `npm i --force`, until this library releases with angular 17 support.

**Comment by ashish-chopra** [comment]
Just uploaded v9.0.0 Someone has to check it by using in a project. I am flying tomorrow will verify later. Thanks!

**Comment by MatthiasWerning** [comment]
@ashish-chopra 

I just tried 9.0.0, works fine for me. Just two small notes: Maybe you could update rxjs to ~7.8.0 as this is also the version range Angular 17 suggests to use. Otherwise @angular/cdk seems to be a v16 major version, v17 should also be available for consistency.
