### ISSUE TITLE
Custom directives not being imported (ngx-gauge-*)

### ISSUE THREAD

**Issue by andyrichardson** [ashish-chopra/ngx-gauge#17]
First off, thanks for the library - it's been a huge help.

## About
I'm currently having an issue where I am able to use the _ngx-gauge_ component, but the associated directives do not work.

## Scope
The following works without a problem

_component.html_

    <ngx-gauge [cap]="'round'" [value]="item.value"></ngx-gauge>

_module.ts_

    import { NgxGaugeModule } from 'ngx-gauge'

    ...

    imports [ NgxGaugeModule ],

    ...

## Reproduction
The following throws an error in the browser.

_component.html_

    <ngx-gauge [cap]="'round'" [value]="item.value">
        <ngx-gauge-value> Test </ngx-gauge-value>
    </ngx-gauge>

_module.ts_

    import { NgxGaugeModule } from 'ngx-gauge'

    ...

    imports [ NgxGaugeModule ],

    ...

### Expected result
Gauge value is changed to text '

### Actual result
Error is produced

    Error: Template parse errors: 'ngx-gauge-value' is not a known element:
        1. If 'ngx-gauge-value' is an Angular component, then verify that it is part of this module.

**Comment by ashish-chopra** [comment]
Hi @andyrichardson 

Make sure you are using ngx-gauge@1.0.0-beta.4 version. I released it in there.
And, check this out, its working fine for the said version: https://stackblitz.com/edit/angular-gnpj9l

Cheers
Ashish

**Comment by andyrichardson** [comment]
Hey @ashish-chopra, thanks for the response.

That's likely the solution, I'll reopen if that isn't the case.
