### ISSUE TITLE
Add option to size fit parent 

### ISSUE THREAD

**Issue by hassondaniel** [ashish-chopra/ngx-gauge#18]
We need to add this to control the size if the parent size changes

**Comment by r-havelka** [comment]
you can do that with css.

````
// HTLM
<ngx-gauge class="gauge-width">

// CSS
.gauge-width {
  width: 100% !important;

  canvas {
    width: 80% !important;
    height: 100% !important;
  }
  .reading-label {
    width: 80% !important;
    height: 100% !important;
  }
}
````

**Comment by yacinebenouniche** [comment]
this is not working, css error: colon expected

**Comment by amairose-papajohns** [comment]
This can be accomplished by binding the `size` attribute to a variable in your component, and setting that variable whenever the window is resized. See this StackBlitz for an example: https://stackblitz.com/edit/angular-xuxawy

**Comment by ashish-chopra** [comment]
Closing this issue as we can acheive it with existing configuration as pointed in the stackblitz. Thanks @amairose-papajohns
