### ISSUE TITLE
how to modify the foregroundColor

### ISSUE THREAD

**Issue by bfheythem** [ashish-chopra/ngx-gauge#21]
I couldn't find a way to edit the foregroundColor and backgroundColor
when I affect a value to them , it tells me that rgba( ...) unknown 
please help me

**Comment by fernandocode** [comment]
You could create an example of the problem at https://stackblitz.com/edit/angular-kaonzk?

**Comment by bfheythem** [comment]
I just want to change the color of the gauge , specify my own color

**Comment by fernandocode** [comment]
@bfheythem, something like that: https://stackblitz.com/edit/angular-xweu2r?file=app/app.component.ts ?

**Comment by ashish-chopra** [comment]
@fernandocode Thanks for sharing an example stackblitz.

@bfheythem You can checkout the example shared by @fernandocode. In case you were trying to do something different, let us know here with snapshot and reproducible stackblitz setup.

Ashish.

**Comment by ShuklaAmitKumar** [comment]
How to change color for gauge value and label ???

**Comment by ashish-chopra** [comment]
@ShuklaAmitKumar You need to use custom directives and pull up values to be displayed there and use your own CSS classes to update it.
