### ISSUE TITLE
guage type full not working

### ISSUE THREAD

**Issue by vignesh007vicky** [ashish-chopra/ngx-gauge#23]
home.component.html

<ngx-gauge 
           [type]="gaugeType" 
           [value]="gaugeValue" 
           [label]="gaugeLabel"  
           [append]="gaugeAppendText"
           >
</ngx-gauge>

home.component.ts

import { NgModule } from '@angular/core';
import { ChartsModule } from 'ng2-charts/ng2-charts';
import { BsDropdownModule } from 'ngx-bootstrap/dropdown';

import { HomeComponent } from './home.component';
import { HomeRoutingModule } from './home-routing.module';
import { NgxGaugeModule } from 'ngx-gauge';

@NgModule({
  imports: [
    HomeRoutingModule,
    ChartsModule,
    BsDropdownModule,
    NgxGaugeModule
  ],
  declarations: [HomeComponent]
})
export class HomeModule { 

  public gaugeType = "full";
  public gaugeValue = 28.3;
  public gaugeLabel = "Speed";
  public gaugeAppendText = "km/hr";
}

it always taking semi type..

**Comment by ShuklaAmitKumar** [comment]
working for me

**Comment by ashish-chopra** [comment]
close the `<ngx-gauge>`  tag with closing `</ngx-gauge>`.
