### ISSUE TITLE
Gauge Meter is not Updated

### ISSUE THREAD

**Issue by nivu** [ashish-chopra/ngx-gauge#24]
While updating the value, only the label alone gets updated, drawing is not happening.

**Comment by nivu** [comment]
Value and Meter is not dynamically updated

**Comment by fernandocode** [comment]
@navneetnivu07 You could create an example of the problem at https://stackblitz.com/edit/angular-kaonzk?

**Comment by nivu** [comment]
@fernandocode In the dev environment, the value alone is updated but the bar didn't update the new value.
But after creating a production build and deploying it works fine.

**Comment by nivu** [comment]
@fernandocode I think some others also facing this issue! Check issues #20(Value drops to 0 after animation). I faced the similar problem.

**Comment by ashish-chopra** [comment]
Closing this issue. As pointed out as duplicate of #20
