### ISSUE TITLE
Adding more then one label inside gauge

### ISSUE THREAD

**Issue by ShuklaAmitKumar** [ashish-chopra/ngx-gauge#25]
What if i want to add more than one label inside gauge???

**Comment by ashish-chopra** [comment]
@ShuklaAmitKumar 

You can use [Custom Directives for Display text](https://github.com/ashish-chopra/ngx-gauge#custom-directives-for-display-text) and can put regular HTML inside it which can span multiple lines. But keep in mind that you have to manage its CSS on your own.

```
<ngx-gauge [value]="currentValue">
    <ngx-gauge-label>
         <div>Label1</div>
         <div>Label 2</div>
    </ngx-gauge-label>
</ngx-gauge>
```
