### ISSUE TITLE
how To change the value of the AppendedText font 

### ISSUE THREAD

**Issue by bfheythem** [ashish-chopra/ngx-gauge#26]
I need to make the text smaller to make it fit inside the gauge : 
![image](https://user-images.githubusercontent.com/22716581/39767815-8486b7bc-52df-11e8-85a4-5b1f380dfc1d.png)

I managed to find where it's located using inspect but don't know how to change it in the code so it would persist  : 
![image](https://user-images.githubusercontent.com/22716581/39768537-7f589326-52e1-11e8-9225-ba8175ceaf10.png)

**Comment by fernandocode** [comment]
I believe that the section ["Custom Directives for display text"](https://github.com/ashish-chopra/ngx-gauge#custom-directives-for-display-text) can help you solve this.

Example: https://stackblitz.com/edit/angular-n2fxlz?file=app%2Fapp.component.html

**Comment by bfheythem** [comment]
@fernandocode  thanks for your help  it worked

Now I want to make the gauge value updated automatically , it gives a real time consumption that is acquired via an API : 
what I did is that the value is displayed but the value wont change only if I refresh the page 
how can I do that ? 
if you want I can share the code for the service I implemented

**Comment by fernandocode** [comment]
@bfheythem,

The Gauge works just like any other angular component, you just need to update the value of the property that the rest angular is responsible.

[Here's a simple example of how the value would be updated.](https://stackblitz.com/edit/angular-ncprzt?file=app/app.component.ts)

This type of doubt can be better remedied by asking the [angular community of stackoverflow](https://stackoverflow.com/questions/tagged/angular) or by searching for your doubt there.

**Comment by ashish-chopra** [comment]
Thank you @fernandocode for answering the question with a superb stackblitz example!
Closing this issue now, as the query has been solved.

@bfheythem In case you have questions on usage you can find answers in README as well as use StackOverflow community. Feel free to discuss anything you want.

Cheers
Ashish

**Comment by galedsoftware** [comment]
If it still matters the following will do the trick

ngx-gauge ::ng-deep .reading-block,
ngx-gauge ::ng-deep .reading-affix {
  font-size: 25px !important;
  font-weight: 500 !important;
}
