### ISSUE TITLE
HighlightJS dependency

### ISSUE THREAD

**Issue by superamadeus** [ashish-chopra/ngx-gauge#28]
`angular2-highlight-js` seems like an unnecessary and unused dependency. Is there some reason it's included?

**Comment by ashish-chopra** [comment]
It is added for building the demo website which is in progress.

**Comment by superamadeus** [comment]
This gauge library is the best out there (in terms of integration w/ Angular 2+). Would it be possible to separate the demo site dependencies from the library's dependencies so that consumers of this project don't have to worry about unneeded dependencies?
