### ISSUE TITLE
Link to demo does not work

### ISSUE THREAD

**Issue by jculverwell** [ashish-chopra/ngx-gauge#3]
https://github.com/ashish-chopra/ngx-gauge

**Comment by ashish-chopra** [comment]
Yup, Demo is not ready yet. But you can follow README, or alternatively you can see the demo of my angular-gauge repository which is the same ngx-gauge but for Angular 1.x versions at https://ashish-chopra.github.io/angular-gauge

**Comment by fernandocode** [comment]
It would be interesting to remove the demo link maybe while it does not work. This causes an impression of abandonment, at least to me.

Perhaps replacing it with a simple stackblitz, for now.

**Comment by pixelsyndicate** [comment]
Yes. I'm a fan of the Angular 1.x version, but not having a demo available here is causing me some trust issues... like perhaps i'm looking at the wrong libraries. I've taken the form from the first demo and converted it to be used in a demo for this version, but I believe the foreground / background isn't being implemented for whatever reason. getting some node exceptions for NgxGauge._getForegroundColorByRange ... kinda works if i enable thresholds... still working to get my own demo working.

**Comment by pixelsyndicate** [comment]
I've completed a demo for this library using the original Angular 1.x version HTML brought in to demo this angular 4+? version.  You can get the example from https://github.com/pixelsyndicate/Angular-xGuage-Playground

**Comment by fernandocode** [comment]
Great job @pixelsyndicate, it was perfect, could be put on the demo link @ashish-chopra. It would also be nice if we could make a demo page available for easy access! :+1: :punch:

**Comment by ashish-chopra** [comment]
Thank you @pixelsyndicate for your efforts. I was in the middle of converting angular 1.x demo to the new angular track and your effort for playground section is really a great help. Right now I am trying to run it on my machine. But I will use it in the actual demo website with proper credits.

Thanks a lot :)
Ashish

**Comment by DJFriar** [comment]
Has there been any progress on this? Looks like the demo is still broken.

**Comment by ashish-chopra** [comment]
Hello All, I have finally uploaded the website with demos and playground section (thanks to @pixelsyndicate). Please check that out.
@pixelsyndicate I have cited you in the footer of the website for your contribution. thank you!

Cheers
Ashish
