### ISSUE TITLE
Adding threshold marker,min,max value

### ISSUE THREAD

**Issue by vinothvarun94** [ashish-chopra/ngx-gauge#30]
it would be more helpful if u add threshold marker,min,max values in gauge and it would be a great addition...

**Comment by YacineGameDev** [comment]
I think this issue is related to #27, isn't it?

**Comment by vinothvarun94** [comment]
yes, nearly.. i m in need of setting labels (threshold).

**Comment by ashish-chopra** [comment]
@vinothvarun94 Right now there is no support to show labels and I am also not planning to add in near future. If you feel to contribute, send a pull request for review. However, your feature request is same as #27, therefore closing it and will track it on 27.

Thanks
Ashish
