### ISSUE TITLE
cannot affect a variable value to the thresholdConfig object

### ISSUE THREAD

**Issue by bfheythem** [ashish-chopra/ngx-gauge#34]
I am trying to create a thresholdConfig where the specified values are affected from certain variable in my class 
It doesn't work apperently the object only accepts values (string/number) , but fails to parse the value of a variable

**Comment by YacineGameDev** [comment]
I created a stackblitz with what I understood from your request: https://stackblitz.com/edit/angular-chi1mt
here the values of the thresholds are variable that can be changed.

**Comment by ashish-chopra** [comment]
Thanks @Observablerxjs!
