### ISSUE TITLE
Updating gauge value is causing a flicker on safari

### ISSUE THREAD

**Issue by tlhsmeenk** [ashish-chopra/ngx-gauge#36]
The gauges are working great on chrome but there seems to be a visual issue while updating the value of the gauge on safari (v11.1). There's some sort of flickering going on (see https://stackblitz.com/edit/angular-aeuw9o). This stops after removing the call to __clear()_ in __update()_ though I haven't really looked into why this is :-) Not sure if there's an issue or I'm making some sort of mistake! I've been using beta 4

**Comment by ashish-chopra** [comment]
Kindly update the ngx-gauge to newest release v1.0.0-beta.8 
I have fixed some issues with gauge drawing and animation code. This might fix the issue.

In case the issue still persists, feel free to reopen it.
