### ISSUE TITLE
Incompatible peer dependencies found

### ISSUE THREAD

**Issue by jruizx** [ashish-chopra/ngx-gauge#38]
I am trying to update angular version from 6 to 7. So I execute the following command:

ng update @angular/cli @angular/core

I receive an error saying Incompatible peer dependencies found. 

                  Package "ngx-gauge" has an incompatible peer dependency to "@angular/core" (requires ">=6.0.0-rc.0 <7.0.0||>=4.3.6 <5.0.0||>=5.0.0 <6.0.0", would install "7.0.4").
                  Package "ngx-gauge" has an incompatible peer dependency to "@angular/common" (requires ">=6.0.0-rc.0 <7.0.0||>=4.3.6 <5.0.0||>=5.0.0 <6.0.0", would install "7.0.4").
Incompatible peer dependencies found. See above.

**Comment by ashish-chopra** [comment]
Thanks, @jruizx for reporting this. I have not tested ngx-gauge with angular 7. If you can do a sanity check and submit a pull request, I would love to merge. Since I can only start working on it after the end of my current academic term after 2nd week of December.

**Comment by cristtopher** [comment]
Same problem to me. waiting for @ashish-chopra

**Comment by ashish-chopra** [comment]
@jruizx and @cristtopher 

The package has been updated to support angular 7. And the source code has also been upgraded to Angular CLI 7. 
Download the latest release `1.0.0-beta.6` using npm install. Report any issue encountered.


Merry Christmas!
Ashish

**Comment by ngx-developer** [comment]
Thanks @ashish-chopra .
