### ISSUE TITLE
forgotten console.log

### ISSUE THREAD

**Issue by r-havelka** [ashish-chopra/ngx-gauge#4]
In *gauge.ts line 105* there is a `console.log('thick value', this.thick);` that wasn't removed. It's nothing major but it is annoying seeing it in my console all the time. If you could remove it, that would be great.

**Comment by ashish-chopra** [comment]
Sure, i will remove that in subsequent releases. But, in case if you can send a pull request, i will be more than happy!! 

Thanks!

**Comment by SpartanNico94** [comment]
You can comment the line that write the thickness in the console editing the file in your node_modules folder.

**Comment by r-havelka** [comment]
I can, but that only works on my local machine. All of my coworkers and our dev environments do their own independent `npm install` and it would be a hassle to be constantly commenting it out. Deleting it in the library would be a much cleaner solution for everyone using the library.

**Comment by ashish-chopra** [comment]
ok @whooguyy, I will do it by tomorrow. I am superly occupied right now.

**Comment by ashish-chopra** [comment]
Console log removed. 

Update to new version `1.0.0-beta.1`
