### ISSUE TITLE
Adding ticks on the gauge 

### ISSUE THREAD

**Issue by neilmaynard** [ashish-chopra/ngx-gauge#41]
I know this is somehow related to issue #27 almost a year ago but does anyone know how to add and display those ticks on the gauge to so it would look like the sample image below. 

![2](https://user-images.githubusercontent.com/40382287/55938451-00239280-5c6e-11e9-957c-f84104409842.jpg)

**Comment by ashish-chopra** [comment]
Closing it. Duplicate of #27
