### ISSUE TITLE
[aria-*] attributes do not match their roles

### ISSUE THREAD

**Issue by chaitanyaVadlamudi** [ashish-chopra/ngx-gauge#45]
When we run audits in chrome using light house, the score of acceessability decreasing because of aria attributes provided in ngx-gauge are mismatching. Can you please provide the correct aria attributes.

Thank you.

**Comment by ashish-chopra** [comment]
Thanks @chaitanyaVadlamudi I will take this issue and support aria-attributes. Would it be possible for you to share what mismatch your system is reporting though?

**Comment by chaitanyaVadlamudi** [comment]
![ngx-err](https://user-images.githubusercontent.com/20918310/57057751-c7a13280-6cc8-11e9-9221-57f3cbedfe07.JPG)
![ngx-err1](https://user-images.githubusercontent.com/20918310/57057761-d2f45e00-6cc8-11e9-8029-7fd097d8293e.JPG)

**Comment by ashish-chopra** [comment]
The Issue has been fixed in version v1.0.0-beta.9. Also, two new aria attributes have been introduced, Please check README.
