### ISSUE TITLE
Bar redrawn to 0 if animation.duration is > 10 (ms)

### ISSUE THREAD

**Issue by yancorrea1995** [ashish-chopra/ngx-gauge#46]
Hi! 

Bar redrawn to 0 but the value is set. This problem only occurs if the animation is true and duration > 10 (ms). I want to use duration ~3000 (s3 seconds), but the bar is crashing. This problem is present in Angular 7.3.1 with ngx-gauge@1.0.0-beta.7. Can you help me to fix this without remove the animation?

Thanks!

**Comment by ashish-chopra** [comment]
@yancorrea1995 I have fixed the bar drawing issue #20 in current release v1.0.0-beta.8. Hopefully it has solved this issue too.

Kindly update your dependency and verify with the new release. Feel free to open if the issue still persists.
