### ISSUE TITLE
Thickness becomes super thin on resize, still. (With example)

### ISSUE THREAD

**Issue by RyanTibbetts-OnScale** [ashish-chopra/ngx-gauge#47]
The chart thickness going thin/removing on dynamic resizing is not solved I think. Maybe this is on me, but I think this is not intended to happen.

https://codesandbox.io/s/angular-puvvt?fontsize=14

**Comment by ashish-chopra** [comment]
Hi @RyanTibbetts-OnScale The issue has been resolved in v1.0.0-beta.10 release.
Kindly update your dependency to the latest. Thanks!

**Comment by RyanTibbetts-OnScale** [comment]
Thanks for the fix Ashish. Best gauge for angular right here buddy.
