### ISSUE TITLE
reading-label container overlaps elements below it (with example)

### ISSUE THREAD

**Issue by schneivo77** [ashish-chopra/ngx-gauge#49]
Hi,

the reading-label div which is created by ngx-gauge when a label is used will overlap elements below it . As an example this results in buttons which are not clickable anymore. I made an example to show the behaviour I mean.

### Example:
https://codesandbox.io/embed/angular-vohdo

### Pictures from chrome dev tools

overlapped:

![overlapped_pic](https://user-images.githubusercontent.com/9406058/59521634-07b12300-8ecd-11e9-91d7-04ac4735719a.PNG)

not overlapped:

![not_overlapped_pic](https://user-images.githubusercontent.com/9406058/59521640-0bdd4080-8ecd-11e9-8070-626dba5033ce.PNG)

**Comment by ashish-chopra** [comment]
The PR has been merged and this issue is fixed. Please update to v1.1.0 compatible with angular 9 to get the fixes. Thanks!
