### ISSUE TITLE
Cannot add the component to Angular 7 project

### ISSUE THREAD

**Issue by gervasiocaj** [ashish-chopra/ngx-gauge#51]
When I added the dependency, the following error was displayed:
```
ERROR in node_modules/ngx-gauge/gauge/gauge-directives.d.ts(3,35): error TS2694: Namespace '".../node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDefWithMeta'.
```

Looking at the declaration files of different versions of `@angular/core`, the exported members (such as `ɵɵDirectiveDefWithMeta`) at the mentioned `gauge-directives.d.ts` file did not exist before version 8.0.x.

https://github.com/angular/angular/blob/6.1.x/tools/public_api_guard/core/core.d.ts
https://github.com/angular/angular/blob/7.2.x/tools/public_api_guard/core/core.d.ts
https://github.com/angular/angular/blob/8.0.x/tools/public_api_guard/core/core.d.ts

**Comment by ashish-chopra** [comment]
Hi @gervasiocaj 

Can you please reproduce the issue and share on Stackblitz, because I need exact version details to start with.

**Comment by RupinSahu** [comment]
> When I added the dependency, the following error was displayed:
> 
> ```
> ERROR in node_modules/ngx-gauge/gauge/gauge-directives.d.ts(3,35): error TS2694: Namespace '".../node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDefWithMeta'.
> ```
> 
> Looking at the declaration files of different versions of `@angular/core`, the exported members (such as `ɵɵDirectiveDefWithMeta`) at the mentioned `gauge-directives.d.ts` file did not exist before version 8.0.x.
> 
> https://github.com/angular/angular/blob/6.1.x/tools/public_api_guard/core/core.d.ts
> https://github.com/angular/angular/blob/7.2.x/tools/public_api_guard/core/core.d.ts
> https://github.com/angular/angular/blob/8.0.x/tools/public_api_guard/core/core.d.ts
**Same error**

**Comment by sankhlepawan** [comment]
++ same issue tryinig to build app 
 /node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDefWithMeta'

i am using angular version 7.2.x

**Comment by tjdiya** [comment]
same issue when trying to build app

**Comment by exile79** [comment]
had the same issue.
Using ngx-gauge@1.0.0-beta.7 worked (current version is beta11)

**Comment by ashish-chopra** [comment]
In order to run ngx-gauge with Angular version 7, ngx-gauge@1.0.0-beta.10 works fine.
