### ISSUE TITLE
Gauge Label can be customised to the fore ground colour of the gauge

### ISSUE THREAD

**Issue by adithyakrishnan21** [ashish-chopra/ngx-gauge#53]
When we customise the gauge to multiple colours based through the threshold functionality, there could also be a feature to add customise the colour of the gauge label to the fore ground colour of the gauge.

**Comment by ashish-chopra** [comment]
I think it can be acheived if you use `<ngx-gauge-label></ngx-gauge-label>` tag and add custom class to it to add color which can change based on the value of the gauge for which a small logic can be written in TS.
