### ISSUE TITLE
Npm package includes ivy compiled metadata - breaking ivy builds

### ISSUE THREAD

**Issue by ly-cultureiq** [ashish-chopra/ngx-gauge#55]
Hi,

The npm package for this project includes metadata from a compilation on angular 8.2 with ivy enabled. This causes any attempt to build with the angular9 next branch to fail with the error `This project was compiled with an earlier version of the ivy compiler - delete node_modules and try again`

Just a simple rebuild after `npm ci` and ivy settings turned off should fix the issue

**Comment by ashish-chopra** [comment]
I will look into this issue during next weekend. However, if you know the fix, can you please post it here or send a pull request?

Thanks!

**Comment by ly-cultureiq** [comment]
i dont htink there is any code fix - beyond upping the release number - 
just run 
`npm ci`
`npm run build:lib`
`npm run pack`
and upload the file in the dist folder
and as long as you dont have any changes from the code in this repo -  it should work perfectly
it seems the last time you ran that code there were changes to test ivy - and thats not in the current codebase.

**Comment by ly-cultureiq** [comment]
i should mention to make sure to delete the current dist folder before running those commands

**Comment by ash-grennan** [comment]
Hi

Just adding that this is also breaking ivy builds too for my project

**Comment by ashish-chopra** [comment]
ngx-gauge@1.0.0-beta.12 can be build with Ivy now with an 8.0.0 version but not yet upgraded to v9.
