### ISSUE TITLE
has no exported member 'ɵɵDirectiveDefWithMeta'

### ISSUE THREAD

**Issue by ravikarthi** [ashish-chopra/ngx-gauge#56]
After integrating ngx-gauge library my app throws exception below

ERROR in node_modules/ngx-gauge/gauge/gauge-directives.d.ts(3,35): error TS2694: Namespace has no exported member 'ɵɵDirectiveDefWithMeta'.

Kindly guide me to solve this issue

**Comment by RichardBoyder** [comment]
This also happens to me... After updating to latest. Please help

**Comment by RichardBoyder** [comment]
Hi guys any news on this?  @ashish-chopra

**Comment by ashish-chopra** [comment]
Hi Richard,

I will look into this issue on weekend.

Hopefully will get some solution. But if you have a solution feel free to
send a PR.

Cheers
Ashish

**Comment by RichardBoyder** [comment]
sure not a problem. thankyou again for you great plugin and all the hard work

**Comment by nfacha** [comment]
Also having this issues

**Comment by akashsherkar** [comment]
Also having the same issue. 
It's breaking my project which is about to go live.
Please help

**Comment by Mark0047** [comment]
I am also having this issue

**Comment by gb37064** [comment]
Same issue.  Following this thread.  BTW I dropped back to the previous version for the time being. Fixed the issue, and my gauge works fine too.

**Comment by qutayba** [comment]
> Same issue. Following this thread. BTW I dropped back to the previous version for the time being. Fixed the issue, and my gauge works fine too.

Same here. I downgraded to the previous version 1.0.0-beta.10 and now its working.

**Comment by Shadowzee** [comment]
Any lead on this? getting same issue.

**Comment by Shadowzee** [comment]
Hi @qutayba  downgrading the version doesn't work for me!!

**Comment by qutayba** [comment]
> 
> 
> Hi @qutayba downgrading the version doesn't work for me!!

In my case downgrading was a fix for the error. I hope we get some updates about the issue soon.

**Comment by ashish-chopra** [comment]
Hello All,

I am not able to reproduce this error, for me, it is working fine. Kindly share details to reproduce the error. However, I have published v1.0.0-beta.12 which removed Ivy compiled files from the build, but not sure if that fixed this issue or not. Let me know, or I will close this issue.
