### ISSUE TITLE
Renderer no longer in @angular/core package 

### ISSUE THREAD

**Issue by favdev** [ashish-chopra/ngx-gauge#58]
`import { SimpleChanges, Renderer, AfterViewInit, ElementRef, OnChanges, OnDestroy } from '@angular/core';
`

Looks like this breaks v9.0.0-rc.2 @angular/core

**Comment by ashish-chopra** [comment]
it's not yet Angular 9 compatible. I will be releasing v9 compatible version shortly.

**Comment by ashish-chopra** [comment]
Angular 9 compatible version released. Use v1.0.0 or later for Angular 9. Thanks!
