### ISSUE TITLE
Value is always redrawn from 0

### ISSUE THREAD

**Issue by ashish-chopra** [ashish-chopra/ngx-gauge#7]
Can we do something so that value should draw from its last position rather than from zero always.

**Comment by jculverwell** [comment]
Thank you, love this component.  Just wondering if you had made any progress on this issue?  If not, is there a way we can turn off the animation.  I've tried setting duration to 0 but it makes the line invisible.  Setting the duration to 1 almost works but it makes it a bit janky.

Thanks again

**Comment by ashish-chopra** [comment]
Yes, I have got a solution. It requires changes in the source code, no outer workarounds can work. I will be adding it today, will release this week positively.

**Comment by jculverwell** [comment]
Thank you, looking forward to the next release.  Thanks again

**Comment by gsteen** [comment]
Hi, any progress on this?

**Comment by ashish-chopra** [comment]
Yes, working on it. I am busy with many parallel works, so hopefully, complete it if no major error occurred.

**Comment by ashish-chopra** [comment]
Hi All,

This issue has been resolved in v1.0.0-beta.2 version which is just released and available on npm.
Update your package of ngx-gauge as soon as possible to see the gauge not redrawing from 0 on every update.

Let me know what you think of it?

Cheers
Ashish

**Comment by yancorrea1995** [comment]
Hi. 
This problem is present in Angular 7.3.1 with ngx-gauge@1.0.0-beta.7. Can you help me to fix this without remove the animation?
