### ISSUE TITLE
Arrow pointer?

### ISSUE THREAD

**Issue by barelabs** [ashish-chopra/ngx-gauge#70]
Hi, thanks for having such an awesome project.  I'm just wondering, do you have any functionality where an arrow can point to the value, such as the arrow in a speedometer.  Thanks so much,

Tim

**Comment by namdao2000** [comment]
This!

**Comment by ashish-chopra** [comment]
Hi All,

Arrow pointer is not in the roadmap for this gauge and does not comply with the user experience of this library.
