### ISSUE TITLE
gauge threshold bug

### ISSUE THREAD

**Issue by SpartanNico94** [ashish-chopra/ngx-gauge#8]
Hi,
I'm using ngx-gauge in my angular application. I have a gauge which max value is 200 and current value is 150 with these thresholds
```
gaugeValue = 150;
gaugeMax = 200;
gaugeThresholds = {
 '0': { color: 'green' },
 '80': { color: 'orange' },
 '100': { color: 'red' } 
};
```

In this case, value is greater than 100 but the second threshold is chosen. If i change from 100 to 99 the right color is selected. This is very strange, can someone help me?

Thanks.

**Comment by SpartanNico94** [comment]
I've checked the source code and when you call NgxGauge.prototype._getForegroundColorByRange you sort thresholds and then you reverse and select the first. Now, suppose you are using my thresholds... if you call .sort() you get 

```
(3) ["0", "100", "80"]
0: "0"
1:"100"
2:"80"
length:3
__proto__:Array(0)
```
This is because you are sorting by strings and not using real number values, so 100 comes before 80. 
To resolve this you should sort by real number. I've changed your code adding a simple function and changing NgxGauge.prototype._getForegroundColorByRange function (inside ngx-gauge.es5.js). Here's my code
```
function sortByNumber(a, b) { return Number(a) > Number(b); }

NgxGauge.prototype._getForegroundColorByRange = function (value) {
        var /** @type {?} */ match = Object.keys(this.thresholds)
            .filter(function (item) { return isNumber(item) && Number(item) <= value; })
			.sort(sortByNumber).reverse()[0];
        return match !== undefined
            ? this.thresholds[match].color || this.foregroundColor
            : this.foregroundColor;
};
```
This solved the problem and gauge will load the proper threshold.

 I'll be glad if you would fix this with a new release, and remove the console.log found in this issue [#4](https://github.com/ashish-chopra/ngx-gauge/issues/4).

Please reply when you fix this so i can download the new version. Thanks :)

**Comment by ashish-chopra** [comment]
Issue Fixed. 

Please update to the new version `v1.0.0-beta.1`.

I will soon release a final version `1.0.0` with an upgrade to ng 5.

**Comment by SpartanNico94** [comment]
Thank you very much
