### ISSUE TITLE
Number format pt-br

### ISSUE THREAD

**Issue by vitorfiler** [ashish-chopra/ngx-gauge#80]
Example
as wish: 10.000,95.

how is 10,000.95

replace does not work

it's possible?

**Comment by AndrewBotsulyak** [comment]
@vitorfiler 
you can customize value as you want
`
<ngx-gauge>
  <ngx-gauge-value>
      {{value}}
    </ngx-gauge-value>
</ngx-gauge>
`
So its not a problem!
