### ISSUE TITLE
Source code for version ngx-guage 1.0.0-beta.13

### ISSUE THREAD

**Issue by rahulmohang** [ashish-chopra/ngx-gauge#83]
Dear team, 

Can you please let me know where I could find source code for the version 1.0.0-beta.13?

Regards,
Rahul

**Comment by ashish-chopra** [comment]
It was somewhere between 1.0.0-beta.11 and 1.1.0 release. The tagging wasn't done for it, however, if you want you can pull out a branch from the commit. Checkout the commit history for that.
