### ISSUE TITLE
Text size issue

### ISSUE THREAD

**Issue by RezaRahmati** [ashish-chopra/ngx-gauge#86]
Hi there

I see texts cropped, is there any mis configuration on my side or it's a defect.

`		<ngx-gauge type="arch"
				   [value]="value"
				   label="Match %"
				   cap="round"
				   [thick]="6"
				   append="%"
				   [animate]="false">
		</ngx-gauge>
`

![image](https://user-images.githubusercontent.com/10086092/95030140-83fbe680-067b-11eb-8e6a-ff5c7705d046.png)

**Comment by lumyus** [comment]
I got the same issue

**Comment by Tyrannmisu** [comment]
I also got the same issue with  angular 11.0.3 and ngx-gauge 1.1.1

**Comment by ashish-chopra** [comment]
I am in the process of upgrading the library with Angular 11.0. I will look into it. Thanks!

**Comment by ashish-chopra** [comment]
`ngx-gauge` is upgraded for angular 11.x.x and I tried the code on my side and it works fine. Please update the library and try it on an empty project with the ngx-gauge code only. If it works fine and still gives you issue in your project code, then it must be some font-size or CSS styling which is messing it up. Kindly share your CSS styling or font-sizing details and re-open the issue.
