### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sarathi0333** [ashish-chopra/ngx-gauge#88]
Hi,

Does ngx-guage supports a range of value as input similar to [https://roundsliderui.com/demos.html#events](url). Whether the slider can be dragged both the direction.

Thanks

**Comment by ashish-chopra** [comment]
Thanks for sharing the idea. `ngx-gauge` is a presentational component that is used to display some value in dial format. However, the round slider like feature to drag the slider to both direction is a user input component which is not what ngx-gauge is designed for. Therefore, this feature does not apply to ngx-gauge.
