### ISSUE TITLE
not able to give threshold

### ISSUE THREAD

**Issue by rashmisnskills** [ashish-chopra/ngx-gauge#90]
Hi Team,
 Im trying to implement angular guage, but im not able to add threshold. 
$scope.threshold = {
                    '0': {color: 'green'},
                    '40': {color: 'orange'},
                    '75.5': {color: 'red'}
                  };                
<ng-gauge size="150" type="arch" thick="20" 
                    min="0" max="120" value="remainingDays" 
                    cap="round" label="Speed" append="mph"
                     thresholds="threshold">
                </ng-gauge> 

some body please help to add this. 
Thanks

**Comment by ashish-chopra** [comment]
Hi, Please follow [this](https://github.com/ashish-chopra/ngx-gauge#configure-threshold-color-ranges) section in the README.
