### ISSUE TITLE
Unable to dynamically change foreground color

### ISSUE THREAD

**Issue by i1zivkovic** [ashish-chopra/ngx-gauge#91]
If the **[value]** property doesn't change then the **foreground** color stays the same.

In the simple example below, on the button click, the foreground stays at the #008888 even though the ng-reflect data is changed to '#000000' when I look in the browser console.

This causes problems because I use it to display negative data with red color and positive data with green color. I use the absolute value for **[value]** since it can't work with negatives but check for **< 0** and **> 0** for the color. In those situations for example -25 and +25 will show the same **[foreground]** color even though the color changed but the absolute value didn't.

```
Component {
public color = '#008888';
}

HTML {
 <ngx-gauge
          [type]="'full'"
          [value]="50 "
          [append]="'% "
          [size]="'80'"
          [cap]="'round'"
          [thick]="6"
          class="align-self-center"
          [max]="60"
          [foregroundColor]="color">
        </ngx-gauge>

<button (click)="color = '#000000'">Change color</button>
}
```

**Comment by ashish-chopra** [comment]
Hi There,

Thanks for reporting the issue. Currently, I am very busy finishing my current project. 
Around the end of February, I will reactivate the next-gauge and fix issues and incorporate feature requests.

Cheers
Ashish

**Comment by ashish-chopra** [comment]
The best way to change the foreground color is to use `thresholds` attribute of `<ngx-gauge></ngx-gauge>`. Check out [this](https://github.com/ashish-chopra/ngx-gauge#configure-threshold-color-ranges) section in the README to learn more.

For your case it will be like this:

```
thresholdConfig = {
    "-60": {color: "red"},
    0: {color: "green"}
  }

```
